// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WorkPermit.DAL.Context;

#nullable disable

namespace WorkPermit.DAL.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WorkPermit.DAL.Models.Activity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("WorkPermitRequestId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WorkPermitRequestId");

                    b.ToTable("Activities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Activity 1",
                            WorkPermitRequestId = 1
                        },
                        new
                        {
                            Id = 2,
                            Description = "Activity 2",
                            WorkPermitRequestId = 1
                        },
                        new
                        {
                            Id = 3,
                            Description = "Activity 3",
                            WorkPermitRequestId = 2
                        },
                        new
                        {
                            Id = 4,
                            Description = "Activity 4",
                            WorkPermitRequestId = 3
                        },
                        new
                        {
                            Id = 5,
                            Description = "Activity 5",
                            WorkPermitRequestId = 1
                        },
                        new
                        {
                            Id = 6,
                            Description = "Activity 6",
                            WorkPermitRequestId = 1
                        });
                });

            modelBuilder.Entity("WorkPermit.DAL.Models.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Department");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "IS"
                        },
                        new
                        {
                            Id = 2,
                            Name = "CS"
                        },
                        new
                        {
                            Id = 3,
                            Name = "DS"
                        });
                });

            modelBuilder.Entity("WorkPermit.DAL.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Mona",
                            Role = "Engineer"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Hossam",
                            Role = "Doctor"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Ali",
                            Role = "Teacher"
                        });
                });

            modelBuilder.Entity("WorkPermit.DAL.Models.Equipment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("WorkPermitRequestId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WorkPermitRequestId");

                    b.ToTable("Equipment");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Equipment 1",
                            WorkPermitRequestId = 1
                        },
                        new
                        {
                            Id = 2,
                            Name = "Equipment 2",
                            WorkPermitRequestId = 2
                        },
                        new
                        {
                            Id = 3,
                            Name = "Equipment 3",
                            WorkPermitRequestId = 1
                        },
                        new
                        {
                            Id = 4,
                            Name = "Equipment 4",
                            WorkPermitRequestId = 1
                        },
                        new
                        {
                            Id = 5,
                            Name = "Equipment 5",
                            WorkPermitRequestId = 3
                        },
                        new
                        {
                            Id = 6,
                            Name = "Equipment 6",
                            WorkPermitRequestId = 2
                        });
                });

            modelBuilder.Entity("WorkPermit.DAL.Models.StatusModel", b =>
                {
                    b.Property<string>("NewStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("StatusModels");
                });

            modelBuilder.Entity("WorkPermit.DAL.Models.WorkPermitRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("DepartmentId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int?>("EmployeeId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("New");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("WorkPermitRequests");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DepartmentId = 1,
                            EmployeeId = 1,
                            EndDate = new DateTime(2022, 1, 2, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2022, 1, 1, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "New"
                        },
                        new
                        {
                            Id = 2,
                            DepartmentId = 2,
                            EmployeeId = 2,
                            EndDate = new DateTime(2022, 1, 4, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2022, 1, 3, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "New"
                        },
                        new
                        {
                            Id = 3,
                            DepartmentId = 3,
                            EmployeeId = 3,
                            EndDate = new DateTime(2022, 1, 6, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2022, 1, 5, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "New"
                        });
                });

            modelBuilder.Entity("WorkPermit.DAL.Models.Activity", b =>
                {
                    b.HasOne("WorkPermit.DAL.Models.WorkPermitRequest", null)
                        .WithMany("Activities")
                        .HasForeignKey("WorkPermitRequestId");
                });

            modelBuilder.Entity("WorkPermit.DAL.Models.Equipment", b =>
                {
                    b.HasOne("WorkPermit.DAL.Models.WorkPermitRequest", null)
                        .WithMany("Equipment")
                        .HasForeignKey("WorkPermitRequestId");
                });

            modelBuilder.Entity("WorkPermit.DAL.Models.WorkPermitRequest", b =>
                {
                    b.HasOne("WorkPermit.DAL.Models.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WorkPermit.DAL.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("WorkPermit.DAL.Models.WorkPermitRequest", b =>
                {
                    b.Navigation("Activities");

                    b.Navigation("Equipment");
                });
#pragma warning restore 612, 618
        }
    }
}
